name: "[internal] Create and Publish Release Docker Image"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  create-docker-image:
      strategy:
        matrix:
          os: [ubuntu-20.04]
          arch: [grayskull, wormhole_b0]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: https://ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Download wheels
          uses: actions/download-artifact@v4
          with:
            name: eager-dist-${{ matrix.os }}-${{ matrix.arch }}
        -name: Get the name of the wheel
          run: |
            echo "WHEEL_FILENAME=$(ls -1 *.whl)" >> $GITHUB_ENV
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            build-args: |
              WHEEL_FILENAME=${{ env.WHEEL_FILENAME }}
              BASE_IMAGE_NAME=tt-metalium/${{ matrix.os }}-amd64
            tags: ghcr.io/${{ github.repository }}/tt-metalium/${{ matrix.os }}-amd64/${{ matrix.arch }}:${{ inputs.version }}
            context: .
            file: dockerfile/release
