name: "Create and Publish Release Docker Image"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  static-checks:
    uses: ./.github/workflows/all-static-checks.yaml
    secrets: inherit
  build-docker-artifact:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
  build-artifact:
    needs: build-docker-artifact
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  publish-release-image:
    needs: build-docker-artifact
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      version: test
