name: "(T3K) T3000 profiler tests"

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 */8 * * *" # This cron schedule runs the workflow every 8 hours

jobs:
  build-artifact-profiler:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      arch: '["wormhole_b0"]'
      tracy: true
    secrets: inherit
  t3000-profiler-tests:
    needs: build-artifact-profiler
    secrets: inherit
    uses: ./.github/workflows/t3000-profiler-tests-impl.yaml
